import { StyleSheet } from 'react-native';
import { colors } from '@/core/theme/colors';
import { fontFamilies } from '@/core/theme/typography';

export const myProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.lightBg,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 36,
    justifyContent: 'space-between',
  },
  // Top Header Row
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    marginTop: 4,
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
  },
  // User Hero Avatar Section
  userHeroSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 10,
  },
  avatarContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.darkGreen,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.gold,
    shadowColor: colors.darkGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  avatarText: {
    fontSize: 27,
    fontFamily: fontFamilies.bold,
    color: colors.gold,
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  editCameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.buttonYellow,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  userNameText: {
    fontSize: 20,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
    letterSpacing: -0.3,
  },
  userBadgeText: {
    fontSize: 12,
    fontFamily: fontFamilies.medium,
    color: colors.textMuted,
    marginTop: 2,
  },
  // Settings List Section
  settingsCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  settingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
  },
  iconBadge: {
    width: 40,
    height: 40,
    borderRadius: 11,
    backgroundColor: colors.mintBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingTitle: {
    fontSize: 15,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
  },
  settingSubtext: {
    fontSize: 13,
    fontFamily: fontFamilies.medium,
    color: colors.textMuted,
    marginTop: 2,
  },
  // Toggle Switch Pill
  togglePill: {
    backgroundColor: colors.buttonYellow,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: colors.buttonYellow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  togglePillOff: {
    backgroundColor: '#EDEEED',
    shadowOpacity: 0,
    elevation: 0,
  },
  toggleText: {
    fontSize: 11,
    fontFamily: fontFamilies.extraBold,
    color: colors.darkGreen,
    letterSpacing: 0.5,
  },
  toggleCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  // Bottom Brand Footer
  bottomBrandSection: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
    marginBottom: 12,
    gap: 6,
  },
  bottomBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bottomBrandText: {
    fontSize: 20,
    fontFamily: fontFamilies.extraBold,
    color: colors.textDark,
    letterSpacing: -0.4,
  },
  bottomAiDot: {
    fontSize: 20,
    fontFamily: fontFamilies.extraBold,
    color: colors.goldDark,
  },
  bottomVersionText: {
    fontSize: 10,
    fontFamily: fontFamilies.bold,
    color: colors.textMuted,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },

  // Buttery-Smooth Animated Bottom Action Sheet Styles
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    zIndex: 2000,
  },
  sheetContainer: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 34,
    zIndex: 2001,
  },
  actionCard: {
    backgroundColor: '#EBEBEB',
    borderRadius: 20,
    overflow: 'hidden',
  },
  actionHeader: {
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderBottomWidth: 0.8,
    borderBottomColor: '#D0D0D0',
  },
  actionHeaderText: {
    fontSize: 13,
    fontFamily: fontFamilies.medium,
    color: '#8E8E93',
  },
  actionOptionBtn: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderBottomWidth: 0.8,
    borderBottomColor: '#D0D0D0',
  },
  actionOptionText: {
    fontSize: 17,
    fontFamily: fontFamilies.semiBold,
    color: '#007AFF',
  },
  actionDestructiveText: {
    fontSize: 17,
    fontFamily: fontFamilies.semiBold,
    color: '#FF3B30',
  },
  cancelCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    marginTop: 10,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  cancelText: {
    fontSize: 17,
    fontFamily: fontFamilies.bold,
    color: '#007AFF',
  },

  // Address & PIN Modals
  fullModalContainer: {
    flex: 1,
    backgroundColor: colors.lightBg,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalHeaderTitle: {
    fontSize: 20,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
  },
  saveModalBtn: {
    backgroundColor: colors.buttonYellow,
    borderRadius: 16,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    shadowColor: colors.buttonYellow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  saveModalBtnText: {
    fontSize: 14,
    fontFamily: fontFamilies.extraBold,
    color: colors.darkGreen,
    letterSpacing: 1.2,
  },
});
