import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '@/core/theme/colors';
import { fontFamilies } from '@/core/theme/typography';

const { width } = Dimensions.get('window');
const BOX_SIZE = Math.min((width - 56 - 40) / 6, 52);

export const otpStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.lightBg,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 24,
    paddingBottom: 36,
    justifyContent: 'space-between',
  },
  // Top Header Row
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    marginTop: 4,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  resendPill: {
    backgroundColor: colors.white,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  resendPillActive: {
    backgroundColor: colors.mintBg,
    borderColor: colors.darkGreen,
  },
  resendPillText: {
    fontSize: 11,
    fontFamily: fontFamilies.bold,
    color: colors.textMuted,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  resendPillTextActive: {
    color: colors.darkGreen,
  },
  // Main Body Section
  mainContent: {
    flex: 1,
    justifyContent: 'center',
    marginVertical: 16,
  },
  iconBadgeWrapper: {
    alignItems: 'center',
    marginBottom: 20,
  },
  iconBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.mintBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(18, 60, 48, 0.12)',
    shadowColor: colors.darkGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  titleText: {
    fontSize: 26,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
    textAlign: 'center',
    marginBottom: 6,
    letterSpacing: -0.4,
  },
  subtitleText: {
    fontSize: 13.5,
    fontFamily: fontFamilies.medium,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: 18,
    lineHeight: 20,
  },
  // Contact Pill Card
  contactPillCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.mintBg,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignSelf: 'center',
    marginBottom: 28,
    borderWidth: 1,
    borderColor: 'rgba(18, 60, 48, 0.12)',
    gap: 8,
  },
  contactPillText: {
    fontSize: 14,
    fontFamily: fontFamilies.bold,
    color: colors.darkGreen,
    letterSpacing: 0.2,
  },
  // 6-Digit OTP Slot Boxes
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
    marginBottom: 24,
  },
  otpBox: {
    width: BOX_SIZE,
    height: 56,
    backgroundColor: colors.white,
    borderRadius: 14,
    textAlign: 'center',
    fontSize: 22,
    fontFamily: fontFamilies.extraBold,
    color: colors.textDark,
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  otpBoxFilled: {
    borderColor: colors.darkGreen,
    backgroundColor: '#F8FCFA',
    shadowColor: colors.darkGreen,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  otpBoxFocused: {
    borderColor: colors.goldDark,
    borderWidth: 2,
  },
  // Resend / Change Phone Footer Row
  changeContactBtn: {
    alignSelf: 'center',
    paddingVertical: 6,
    marginTop: 4,
  },
  changeContactText: {
    fontSize: 12,
    fontFamily: fontFamilies.bold,
    color: colors.textMuted,
    letterSpacing: 0.5,
    textDecorationLine: 'underline',
  },
  // Verify Primary Action Button
  verifyBtn: {
    backgroundColor: colors.buttonYellow,
    borderRadius: 16,
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: colors.buttonYellow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: 12,
  },
  verifyBtnDisabled: {
    backgroundColor: '#E2E7ED',
    shadowOpacity: 0,
    elevation: 0,
  },
  verifyBtnText: {
    fontSize: 15,
    fontFamily: fontFamilies.extraBold,
    letterSpacing: 1.2,
    color: colors.darkGreen,
  },
  verifyBtnTextDisabled: {
    color: colors.textMuted,
  },
});
