import { StyleSheet } from 'react-native';
import { colors } from '@/core/theme/colors';
import { fontFamilies } from '@/core/theme/typography';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.lightBg,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 48,
  },
  // Top Header Row
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    marginTop: 6,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#EDEEED',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#EDEEED',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.gold,
  },
  greetingCol: {
    justifyContent: 'center',
  },
  greetingSub: {
    fontSize: 12,
    fontFamily: fontFamilies.regular,
    color: colors.textMuted,
  },
  greetingName: {
    fontSize: 15.5,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
  },
  // Loyalty Points Reward Card
  rewardCard: {
    backgroundColor: '#1E3C36',
    borderRadius: 20,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginTop: 4,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(152, 203, 255, 0.15)',
  },
  rewardIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardContent: {
    flex: 1,
  },
  rewardPointsRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  rewardPointsNumber: {
    fontSize: 21,
    fontFamily: fontFamilies.extraBold,
    color: colors.white,
  },
  rewardPointsLabel: {
    fontSize: 12,
    fontFamily: fontFamilies.medium,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  rewardExpiringText: {
    fontSize: 10.5,
    fontFamily: fontFamilies.regular,
    color: 'rgba(255, 255, 255, 0.65)',
    marginTop: 2,
  },
  // Finance Calculator Card
  calculatorCard: {
    backgroundColor: '#5C8276',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 26,
  },
  calcLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  calcIconBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calcTitle: {
    fontSize: 15,
    fontFamily: fontFamilies.bold,
    color: colors.white,
  },

  // Section Label
  sectionLabel: {
    fontSize: 11,
    fontFamily: fontFamilies.bold,
    color: colors.textMuted,
    letterSpacing: 1.0,
    textTransform: 'uppercase',
    marginBottom: 14,
    marginTop: 10,
  },

  // --- ONGOING / UPCOMING APPLICATION CARD UI ---
  ongoingCard: {
    width: '100%',
    minHeight: 140,
    borderRadius: 18,
    backgroundColor: '#537997',
    paddingHorizontal: 18,
    paddingVertical: 16,
    justifyContent: 'space-between',
    marginTop: 4,
    marginBottom: 22,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
    overflow: 'hidden',
  },
  ongoingTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inProcessBadge: {
    backgroundColor: '#D99B26',
    paddingHorizontal: 13,
    paddingVertical: 4.5,
    borderRadius: 12,
  },
  inProcessText: {
    fontSize: 10.5,
    fontFamily: fontFamilies.bold,
    color: colors.white,
  },
  awaitingBadge: {
    backgroundColor: '#3182CE',
    paddingHorizontal: 13,
    paddingVertical: 4.5,
    borderRadius: 12,
  },
  awaitingText: {
    fontSize: 10.5,
    fontFamily: fontFamilies.bold,
    color: colors.white,
  },
  categoryWhitePill: {
    backgroundColor: colors.white,
    paddingHorizontal: 13,
    paddingVertical: 4.5,
    borderRadius: 12,
  },
  categoryWhitePillText: {
    fontSize: 10.5,
    fontFamily: fontFamilies.bold,
    color: '#2D3748',
  },
  ongoingTitle: {
    fontSize: 15.5,
    fontFamily: fontFamilies.extraBold,
    color: colors.white,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginVertical: 10,
  },
  ongoingBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ongoingRefId: {
    fontSize: 11,
    fontFamily: fontFamilies.medium,
    color: 'rgba(255, 255, 255, 0.85)',
  },
  ongoingRefIdBold: {
    fontFamily: fontFamilies.bold,
    color: colors.white,
  },
  ongoingLastEdit: {
    fontSize: 10.5,
    fontFamily: fontFamilies.medium,
    color: 'rgba(255, 255, 255, 0.85)',
  },

  // --- UPCOMING CARDS (LEGACY FALLBACK) UI ---
  upcomingCardDark: {
    width: '100%',
    height: 144,
    borderRadius: 18,
    backgroundColor: '#251C33',
    paddingHorizontal: 18,
    paddingVertical: 16,
    justifyContent: 'space-between',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 4,
    overflow: 'hidden',
  },
  upcomingCardBlue: {
    width: '100%',
    height: 144,
    borderRadius: 18,
    backgroundColor: '#537997',
    paddingHorizontal: 18,
    paddingVertical: 16,
    justifyContent: 'space-between',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 4,
    overflow: 'hidden',
  },
  upcomingTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  issuerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  issuerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  issuerTextColumn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  upcomingIssuerText: {
    fontSize: 16,
    fontFamily: fontFamilies.extraBold,
    color: colors.white,
    letterSpacing: 0.5,
  },
  upcomingIssuerSub: {
    fontSize: 10,
    fontFamily: fontFamilies.medium,
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 12,
  },
  upcomingPillBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 13,
    paddingVertical: 4.5,
    borderRadius: 14,
  },
  upcomingPillText: {
    fontSize: 10.5,
    fontFamily: fontFamilies.bold,
    color: '#2D3748',
  },
  upcomingCenterRow: {
    marginTop: 6,
  },
  upcomingAmountText: {
    fontSize: 22,
    fontFamily: fontFamilies.extraBold,
    color: colors.white,
    letterSpacing: 0.5,
  },
  upcomingAmountSub: {
    fontSize: 11,
    fontFamily: fontFamilies.medium,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: 2,
  },
  upcomingBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  upcomingBottomRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 4,
  },
  upcomingBottomText: {
    fontSize: 11,
    fontFamily: fontFamilies.medium,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  upcomingBottomTextBold: {
    fontFamily: fontFamilies.bold,
    color: colors.white,
  },

  // Promo Card Container
  promoCardContainer: {
    backgroundColor: colors.white,
    borderRadius: 20,
    overflow: 'hidden',
    marginTop: 4,
    marginBottom: 22,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  lightGraphicBanner: {
    width: '100%',
    height: 165,
    backgroundColor: '#F0F3F5',
    overflow: 'hidden',
    position: 'relative',
  },
  bannerImage: {
    width: '100%',
    height: '100%',
  },

  // Mapped Product Badges
  cardOverlayHeader: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bankBadge: {
    backgroundColor: 'rgba(18, 60, 48, 0.88)',
    paddingHorizontal: 11,
    paddingVertical: 4.5,
    borderRadius: 10,
  },
  bankBadgeText: {
    fontSize: 10.5,
    fontFamily: fontFamilies.bold,
    color: colors.gold,
    letterSpacing: 0.5,
  },
  ratingBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 3.5,
    borderRadius: 10,
  },
  ratingBadgeText: {
    fontSize: 11,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
  },

  // Text Section Boxes
  infoBoxMint: {
    padding: 18,
    backgroundColor: '#EEF8F3',
  },
  infoBoxCream: {
    padding: 18,
    backgroundColor: '#F7F7EE',
  },
  categoryTag: {
    fontSize: 10,
    fontFamily: fontFamilies.bold,
    color: colors.darkGreen,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  cardTitle: {
    fontSize: 15.5,
    fontFamily: fontFamilies.bold,
    color: colors.textDark,
    letterSpacing: -0.2,
    marginBottom: 4,
  },
  cardSubtext: {
    fontSize: 12,
    fontFamily: fontFamilies.regular,
    color: colors.textMuted,
    lineHeight: 18,
  },

  // Fee Pill Row
  feeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 8,
  },
  feePill: {
    backgroundColor: 'rgba(18, 60, 48, 0.08)',
    paddingHorizontal: 9,
    paddingVertical: 3.5,
    borderRadius: 7,
  },
  feePillText: {
    fontSize: 10.5,
    fontFamily: fontFamilies.semiBold,
    color: colors.darkGreen,
  },

  // Special Offer Card
  promoOfferCard: {
    flexDirection: 'row',
    backgroundColor: '#EEF8F3',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(18, 60, 48, 0.12)',
    marginTop: 4,
    marginBottom: 8,
  },
  promoIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: colors.darkGreen,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoText: {
    flex: 1,
    fontSize: 12,
    fontFamily: fontFamilies.semiBold,
    color: colors.textDark,
    lineHeight: 16,
  },
});
